### ISSUE TITLE
how to run posture?

### ISSUE THREAD

**Issue by m3m3-chan** [izzy-nicholson/CreatED#1]
Hi, 
interesting work?
I want to know how to run posutre.py ? I have issues with the ` port = "/dev/ttyACM1"` what does that refer to? 
right now I'm getting the following error:
```
\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '/dev/ttyACM1': FileNotFoundError(2, 'The system cannot find the path specified.', None, 3)
```

any solution ? 
Thanks,

**Comment by pqzx** [comment]
Hi, thanks for the interest.
This was a while ago and I don't have any of the hardware anymore, but from what I remember we ran it with 3 microbit microcontrollers. Load one of each of the following on separate microbits:
`SatelliteLeftShoulder.py`
`SatelliteRightShoulder.py`
`Receiver.py`

The two microbits running the `Satellite...py` are attached to each shoulder of the user. The receiver is connected to the computer where you run the main program. 

Then run `post2.py` to start.
If you want to plot the measurements you collected during monitoring, you can run `plotty2.py`

`port` refers to the port the microbit running `Receiver.py` is connected on. The error you're getting suggests you're missing/haven't connected the hardware.

**Comment by m3m3-chan** [comment]
thanks for the reply!
